CREATE TABLE historico_mensagens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_id VARCHAR(50) REFERENCES usuarios(whatsapp_id) NOT NULL,
  remetente VARCHAR(10) NOT NULL, -- 'usuario' ou 'ia'
  conteudo TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
);